name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "build.zig"
  pull_request:
    branches:
      - main
      - "feature/**"
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "build.zig"

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxxf86vm-dev \
            libxcursor-dev \
            libxinerama-dev \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libwayland-dev \
            libwayland-egl1-mesa \
            libdrm-dev \
            libgbm-dev

      - name: Run Tests (Debug)
        run: |
          zig build test

      - name: Run tests (Release)
        run: |
          zig build test --release=fast
