name: Formatting

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - '.github/workflows/format.yml'
      - 'src/**'
      - 'build.zig'
      - 'build.zig.zon'
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths:
      - '.github/workflows/format.yml'
      - 'src/**'
      - 'build.zig'
      - 'build.zig.zon'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Check formatting
        run: zig build lint
